---  #Handlers Playbook
- hosts: all
- user: ansible
- become: yes
- connection: ssh
- gather_facts: yes
  tasks:
    - name: Install httpd server
      action: yum name=httpd state=installed
      notify: restart HTTPD

  handlers:
    - name: restart HTTPD
      action: service name=httpd state=restarted