--- #variable playbook
- hosts: all
  user: ansible
  become: yes
  connection: ssh
  vars:
    pkglinux: httpd
    
  tasks:
    - name: Install package in Linux servers
      action: yum name='{{pkglinux}}' state=installed 
